### ISSUE TITLE
check that all functions are used

### ISSUE THREAD

**Issue by chrishavlin** [guypaxman/vbr_bayesian_inversion#8]

**Comment by guypaxman** [comment]
In the three folders, the following files ARE currently used:

/GLAD25
- VS_Model.mat
- QL6_Model.mat
These are the data input files, which I suspect we won't provide in the finalised repository - can provide weblinks to the places the user can access the data instead.

/functions
- make_param_grid.m
- make_sweep.m
- generate_parameter_sweep_HL.m
The make_sweep.m script generates the sweep .mat file (using generate_parameter_sweep_HL.m). The make_param_grid.m function converts the sweep box .mat file into the 'box' of thermodynamic state parameters to be swept by the VBR within the main inversion script. It would be good to combine or streamline these functions to make their usage easier to follow.

/inv_functions
- make_X0.m
- make_F.m
- make_Vd.m
- make_Vm.m
- calc_yres.m
- find_idx.m
These functions calculate the different matrices / vectors used in the inversion. All other files (with '_vsonly' at the end) are not required. There are different versions of 'make_X0.m' for the different anelasticm models, but in reality only one is needed. I can tidy this up.

**Comment by chrishavlin** [comment]
after #15 goes in, I think we should be OK to delete all the functions that are not used (with the caveat that we don't want to delete the new functions that I've added). I also think we could move all the functions to a single folder and just keep the `run_*.m` files at the top level.

**Comment by chrishavlin** [comment]
#17 deletes everything not mentioned above (except any new functions added since the list was compiled)!
